/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Tiago
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOgo = new javax.swing.JLabel();
        menulistadeprodutos = new javax.swing.JButton();
        menuajuda = new javax.swing.JButton();
        bemvindos = new javax.swing.JButton();
        menucotações = new javax.swing.JButton();
        menurelatorio = new javax.swing.JButton();
        menufornecedores = new javax.swing.JButton();
        painelMenu = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barramenu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boas Vindas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Logo Siaco.png"))); // NOI18N
        getContentPane().add(LOgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menulistadeprodutos.setBackground(new java.awt.Color(0, 0, 0));
        menulistadeprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 70.png"))); // NOI18N
        getContentPane().add(menulistadeprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 90));

        menuajuda.setBackground(new java.awt.Color(0, 0, 0));
        menuajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 75.png"))); // NOI18N
        getContentPane().add(menuajuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 350, 90));

        bemvindos.setBackground(new java.awt.Color(0, 0, 0));
        bemvindos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 12.png"))); // NOI18N
        bemvindos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bemvindosActionPerformed(evt);
            }
        });
        getContentPane().add(bemvindos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 90));

        menucotações.setBackground(new java.awt.Color(0, 0, 0));
        menucotações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 14.png"))); // NOI18N
        getContentPane().add(menucotações, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 350, 90));

        menurelatorio.setBackground(new java.awt.Color(0, 0, 0));
        menurelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 15.png"))); // NOI18N
        getContentPane().add(menurelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 350, 90));

        menufornecedores.setBackground(new java.awt.Color(0, 0, 0));
        menufornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Grupo 74.png"))); // NOI18N
        getContentPane().add(menufornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 350, 90));

        painelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Retângulo 7.png"))); // NOI18N
        getContentPane().add(painelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 1050));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/todas/boasvindas/Background geral.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1590, 1190));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        barramenu.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        jMenu3.setText("Arquivo");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barramenu.add(jMenu3);

        jMenu4.setText("Exibir");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barramenu.add(jMenu4);

        jMenu5.setText("Filtros ");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barramenu.add(jMenu5);

        jMenu6.setText("Configurações");
        jMenu6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barramenu.add(jMenu6);

        jMenu7.setText("Ajuda");
        jMenu7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barramenu.add(jMenu7);

        setJMenuBar(barramenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bemvindosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bemvindosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bemvindosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOgo;
    private javax.swing.JLabel background;
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JButton bemvindos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JButton menuajuda;
    private javax.swing.JButton menucotações;
    private javax.swing.JButton menufornecedores;
    private javax.swing.JButton menulistadeprodutos;
    private javax.swing.JButton menurelatorio;
    private javax.swing.JLabel painelMenu;
    // End of variables declaration//GEN-END:variables
}
